//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallMember
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public string identity { get; set; }
        public string dispname { get; set; }
        public string languages { get; set; }
        public Nullable<long> call_duration { get; set; }
        public Nullable<long> price_per_minute { get; set; }
        public Nullable<long> price_precision { get; set; }
        public string price_currency { get; set; }
        public string payment_category { get; set; }
        public Nullable<long> type { get; set; }
        public Nullable<long> status { get; set; }
        public Nullable<long> failurereason { get; set; }
        public Nullable<long> sounderror_code { get; set; }
        public Nullable<long> soundlevel { get; set; }
        public string pstn_statustext { get; set; }
        public string pstn_feedback { get; set; }
        public string forward_targets { get; set; }
        public string forwarded_by { get; set; }
        public string debuginfo { get; set; }
        public Nullable<long> videostatus { get; set; }
        public string target_identity { get; set; }
        public Nullable<long> mike_status { get; set; }
        public Nullable<long> is_read_only { get; set; }
        public Nullable<long> quality_status { get; set; }
        public string call_name { get; set; }
        public Nullable<long> transfer_status { get; set; }
        public Nullable<long> transfer_active { get; set; }
        public string transferred_by { get; set; }
        public string transferred_to { get; set; }
        public string guid { get; set; }
        public Nullable<long> next_redial_time { get; set; }
        public Nullable<long> nrof_redials_done { get; set; }
        public Nullable<long> nrof_redials_left { get; set; }
        public string transfer_topic { get; set; }
        public string real_identity { get; set; }
        public Nullable<long> start_timestamp { get; set; }
        public Nullable<long> is_conference { get; set; }
        public string quality_problems { get; set; }
        public Nullable<long> identity_type { get; set; }
        public string country { get; set; }
        public Nullable<long> creation_timestamp { get; set; }
        public string stats_xml { get; set; }
        public Nullable<long> is_premium_video_sponsor { get; set; }
        public Nullable<long> is_multiparty_video_capable { get; set; }
        public Nullable<long> recovery_in_progress { get; set; }
        public string nonse_word { get; set; }
        public Nullable<long> pk_status { get; set; }
        public Nullable<long> call_db_id { get; set; }
        public Nullable<long> prime_status { get; set; }
    }
}
