//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public Nullable<long> begin_timestamp { get; set; }
        public string topic { get; set; }
        public Nullable<long> is_muted { get; set; }
        public Nullable<long> is_unseen_missed { get; set; }
        public string host_identity { get; set; }
        public Nullable<long> mike_status { get; set; }
        public Nullable<long> duration { get; set; }
        public Nullable<long> soundlevel { get; set; }
        public string access_token { get; set; }
        public Nullable<long> active_members { get; set; }
        public Nullable<long> is_active { get; set; }
        public string name { get; set; }
        public Nullable<long> video_disabled { get; set; }
        public Nullable<long> joined_existing { get; set; }
        public string server_identity { get; set; }
        public Nullable<long> vaa_input_status { get; set; }
        public Nullable<long> is_incoming { get; set; }
        public Nullable<long> is_conference { get; set; }
        public Nullable<long> is_on_hold { get; set; }
        public Nullable<long> start_timestamp { get; set; }
        public string quality_problems { get; set; }
        public string current_video_audience { get; set; }
        public Nullable<long> premium_video_status { get; set; }
        public Nullable<long> premium_video_is_grace_period { get; set; }
        public Nullable<long> is_premium_video_sponsor { get; set; }
        public string premium_video_sponsor_list { get; set; }
        public byte[] old_members { get; set; }
        public string partner_handle { get; set; }
        public string partner_dispname { get; set; }
        public Nullable<long> type { get; set; }
        public Nullable<long> status { get; set; }
        public Nullable<long> failurereason { get; set; }
        public Nullable<long> failurecode { get; set; }
        public string pstn_number { get; set; }
        public Nullable<long> old_duration { get; set; }
        public byte[] conf_participants { get; set; }
        public string pstn_status { get; set; }
        public byte[] members { get; set; }
        public Nullable<long> conv_dbid { get; set; }
    }
}
