//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMember
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public string chatname { get; set; }
        public string identity { get; set; }
        public Nullable<long> role { get; set; }
        public Nullable<long> is_active { get; set; }
        public Nullable<long> cur_activities { get; set; }
        public string adder { get; set; }
    }
}
