//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long id { get; set; }
        public string skypename { get; set; }
        public string fullname { get; set; }
        public Nullable<long> birthday { get; set; }
        public Nullable<long> gender { get; set; }
        public string languages { get; set; }
        public string country { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string ipcountry { get; set; }
        public string displayname { get; set; }
        public Nullable<long> isblocked { get; set; }
    }
}
