//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactGroup
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public Nullable<long> type { get; set; }
        public Nullable<long> custom_group_id { get; set; }
        public string given_displayname { get; set; }
        public Nullable<long> nrofcontacts { get; set; }
        public Nullable<long> nrofcontacts_online { get; set; }
        public Nullable<long> given_sortorder { get; set; }
        public Nullable<long> type_old { get; set; }
        public string proposer { get; set; }
        public string description { get; set; }
        public string associated_chat { get; set; }
        public string members { get; set; }
        public Nullable<long> cbl_id { get; set; }
        public byte[] cbl_blob { get; set; }
        public Nullable<long> @fixed { get; set; }
        public Nullable<long> keep_sharedgroup_contacts { get; set; }
        public string chats { get; set; }
        public Nullable<long> extprop_is_hidden { get; set; }
        public Nullable<long> extprop_sortorder_value { get; set; }
        public Nullable<long> extprop_is_expanded { get; set; }
    }
}
