//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<CallMember> CallMembers { get; set; }
        public DbSet<Call> Calls { get; set; }
        public DbSet<ChatMember> ChatMembers { get; set; }
        public DbSet<Chat> Chats { get; set; }
        public DbSet<ContactGroup> ContactGroups { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<ConversationEntity> Conversations { get; set; }
        public DbSet<DbMeta> DbMetas { get; set; }
        public DbSet<LegacyMessage> LegacyMessages { get; set; }
        public DbSet<MessageEntity> Messages { get; set; }
        public DbSet<Participant> Participants { get; set; }
        public DbSet<SMS> SMSes { get; set; }
        public DbSet<Transfer> Transfers { get; set; }
        public DbSet<Video> Videos { get; set; }
        public DbSet<Voicemail> Voicemails { get; set; }
    }
}
