//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageEntity
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public long convo_id { get; set; }
        public string chatname { get; set; }
        public string author { get; set; }
        public string from_dispname { get; set; }
        public Nullable<long> author_was_live { get; set; }
        public byte[] guid { get; set; }
        public string dialog_partner { get; set; }
        public Nullable<long> timestamp { get; set; }
        public Nullable<long> type { get; set; }
        public Nullable<long> sending_status { get; set; }
        public Nullable<long> consumption_status { get; set; }
        public string edited_by { get; set; }
        public Nullable<long> edited_timestamp { get; set; }
        public Nullable<long> param_key { get; set; }
        public Nullable<long> param_value { get; set; }
        public string body_xml { get; set; }
        public string identities { get; set; }
        public string reason { get; set; }
        public Nullable<long> leavereason { get; set; }
        public Nullable<long> participant_count { get; set; }
        public Nullable<long> error_code { get; set; }
        public Nullable<long> chatmsg_type { get; set; }
        public Nullable<long> chatmsg_status { get; set; }
        public Nullable<long> body_is_rawxml { get; set; }
        public Nullable<long> oldoptions { get; set; }
        public Nullable<long> newoptions { get; set; }
        public Nullable<long> newrole { get; set; }
        public Nullable<long> pk_id { get; set; }
        public Nullable<long> crc { get; set; }
        public Nullable<long> remote_id { get; set; }
        public string call_guid { get; set; }
        public string extprop_contact_review_date { get; set; }
        public Nullable<long> extprop_contact_received_stamp { get; set; }
        public Nullable<long> extprop_contact_reviewed { get; set; }
    
        public virtual ConversationEntity Conversation { get; set; }
    }
}
