//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public Nullable<long> type { get; set; }
        public Nullable<long> status { get; set; }
        public Nullable<long> failurereason { get; set; }
        public Nullable<long> is_failed_unseen { get; set; }
        public Nullable<long> timestamp { get; set; }
        public Nullable<long> price { get; set; }
        public Nullable<long> price_precision { get; set; }
        public string price_currency { get; set; }
        public string reply_to_number { get; set; }
        public string target_numbers { get; set; }
        public byte[] target_statuses { get; set; }
        public string body { get; set; }
        public Nullable<long> chatmsg_id { get; set; }
        public string identity { get; set; }
        public Nullable<long> notification_id { get; set; }
        public Nullable<long> event_flags { get; set; }
        public Nullable<long> extprop_hide_from_history { get; set; }
        public Nullable<long> extprop_extended { get; set; }
    }
}
