//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public Nullable<long> type { get; set; }
        public string partner_handle { get; set; }
        public string partner_dispname { get; set; }
        public Nullable<long> status { get; set; }
        public Nullable<long> failurereason { get; set; }
        public Nullable<long> starttime { get; set; }
        public Nullable<long> finishtime { get; set; }
        public string filepath { get; set; }
        public string filename { get; set; }
        public string filesize { get; set; }
        public string bytestransferred { get; set; }
        public Nullable<long> bytespersecond { get; set; }
        public byte[] chatmsg_guid { get; set; }
        public Nullable<long> chatmsg_index { get; set; }
        public Nullable<long> convo_id { get; set; }
        public Nullable<long> pk_id { get; set; }
        public byte[] nodeid { get; set; }
        public Nullable<long> last_activity { get; set; }
        public Nullable<long> flags { get; set; }
        public Nullable<long> old_status { get; set; }
        public Nullable<long> old_filepath { get; set; }
        public Nullable<long> accepttime { get; set; }
        public string extprop_localfilename { get; set; }
        public Nullable<long> extprop_hide_from_history { get; set; }
        public Nullable<long> extprop_window_visible { get; set; }
        public Nullable<long> extprop_handled_by_chat { get; set; }
    }
}
