//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public Nullable<long> status { get; set; }
        public string error { get; set; }
        public string debuginfo { get; set; }
        public string dimensions { get; set; }
        public Nullable<long> media_type { get; set; }
        public Nullable<long> duration_1080 { get; set; }
        public Nullable<long> duration_720 { get; set; }
        public Nullable<long> duration_hqv { get; set; }
        public Nullable<long> duration_vgad2 { get; set; }
        public Nullable<long> duration_ltvgad2 { get; set; }
        public Nullable<long> timestamp { get; set; }
        public Nullable<long> hq_present { get; set; }
        public Nullable<long> duration_ss { get; set; }
        public Nullable<long> ss_timestamp { get; set; }
        public Nullable<long> convo_id { get; set; }
        public string device_path { get; set; }
    }
}
